name: app-bzod

services:
  bzod:
    image: nx9-url-shortener:v0.1.0

    build:
      context: .
      dockerfile: Dockerfile

    container_name: bzod

    environment:
      - COOKIE_SECURE=false
      - DATA_DIR=/app/data
      - HOST=0.0.0.0
      - PORT=8654
      - RUST_LOG=info

    ports:
      - mode: ingress
        target: 8654
        published: "8654"
        protocol: tcp

    restart: unless-stopped

    volumes:
      - type: bind
        source: /DATA/AppData/bzod/data
        target: /app/data
        bind:
          create_host_path: true

      - type: bind
        source: /DATA/AppData/bzod/config
        target: /app/config
        bind:
          create_host_path: true

    networks:
      - default

    hostname: bzod
    privileged: false

    cpu_shares: 90

    deploy:
      resources:
        limits:
          memory: 31940M

networks:
  default:
    name: app_default

x-casaos:
  hostname: ""
  scheme: http
  index: /
  port_map: "8654"
  author: self
  category: self
  icon: ""
  title:
    custom: nx9-url-shortener
